// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidaturas.sql

package bd

import (
	"context"
	"time"
)

const apagarCandidatura = `-- name: ApagarCandidatura :execrows
delete from candidatura where id = $1
`

func (q *Queries) ApagarCandidatura(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, apagarCandidatura, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarCandidatura = `-- name: BuscarCandidatura :one
select id, empresa, vaga, link, criada_em, fonte, modalidade, salario, anotacoes, etapa, atualizada_em from candidatura where id = $1
`

func (q *Queries) BuscarCandidatura(ctx context.Context, id int64) (Candidatura, error) {
	row := q.db.QueryRow(ctx, buscarCandidatura, id)
	var i Candidatura
	err := row.Scan(
		&i.ID,
		&i.Empresa,
		&i.Vaga,
		&i.Link,
		&i.CriadaEm,
		&i.Fonte,
		&i.Modalidade,
		&i.Salario,
		&i.Anotacoes,
		&i.Etapa,
		&i.AtualizadaEm,
	)
	return i, err
}

const criarCandidatura = `-- name: CriarCandidatura :one
insert into candidatura (empresa, vaga, link, fonte, modalidade, salario, anotacoes, etapa)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, empresa, vaga, link, criada_em, fonte, modalidade, salario, anotacoes, etapa, atualizada_em
`

type CriarCandidaturaParams struct {
	Empresa    string
	Vaga       string
	Link       *string
	Fonte      *string
	Modalidade *string
	Salario    *string
	Anotacoes  *string
	Etapa      string
}

func (q *Queries) CriarCandidatura(ctx context.Context, arg CriarCandidaturaParams) (Candidatura, error) {
	row := q.db.QueryRow(ctx, criarCandidatura,
		arg.Empresa,
		arg.Vaga,
		arg.Link,
		arg.Fonte,
		arg.Modalidade,
		arg.Salario,
		arg.Anotacoes,
		arg.Etapa,
	)
	var i Candidatura
	err := row.Scan(
		&i.ID,
		&i.Empresa,
		&i.Vaga,
		&i.Link,
		&i.CriadaEm,
		&i.Fonte,
		&i.Modalidade,
		&i.Salario,
		&i.Anotacoes,
		&i.Etapa,
		&i.AtualizadaEm,
	)
	return i, err
}

const editarCandidatura = `-- name: EditarCandidatura :one
update candidatura
set empresa = $1, vaga = $2, link = $3, fonte = $4, modalidade = $5,
    salario = $6, anotacoes = $7, atualizada_em = now()
where id = $8
returning id, empresa, vaga, link, criada_em, fonte, modalidade, salario, anotacoes, etapa, atualizada_em
`

type EditarCandidaturaParams struct {
	Empresa    string
	Vaga       string
	Link       *string
	Fonte      *string
	Modalidade *string
	Salario    *string
	Anotacoes  *string
	ID         int64
}

func (q *Queries) EditarCandidatura(ctx context.Context, arg EditarCandidaturaParams) (Candidatura, error) {
	row := q.db.QueryRow(ctx, editarCandidatura,
		arg.Empresa,
		arg.Vaga,
		arg.Link,
		arg.Fonte,
		arg.Modalidade,
		arg.Salario,
		arg.Anotacoes,
		arg.ID,
	)
	var i Candidatura
	err := row.Scan(
		&i.ID,
		&i.Empresa,
		&i.Vaga,
		&i.Link,
		&i.CriadaEm,
		&i.Fonte,
		&i.Modalidade,
		&i.Salario,
		&i.Anotacoes,
		&i.Etapa,
		&i.AtualizadaEm,
	)
	return i, err
}

const historicoDaCandidatura = `-- name: HistoricoDaCandidatura :many
select id, candidatura_id, de, para, em, observacao from etapa_historico where candidatura_id = $1 order by em, id
`

func (q *Queries) HistoricoDaCandidatura(ctx context.Context, candidaturaID int64) ([]EtapaHistorico, error) {
	rows, err := q.db.Query(ctx, historicoDaCandidatura, candidaturaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EtapaHistorico
	for rows.Next() {
		var i EtapaHistorico
		if err := rows.Scan(
			&i.ID,
			&i.CandidaturaID,
			&i.De,
			&i.Para,
			&i.Em,
			&i.Observacao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarCandidaturas = `-- name: ListarCandidaturas :many
select candidatura.id, candidatura.empresa, candidatura.vaga, candidatura.link, candidatura.criada_em, candidatura.fonte, candidatura.modalidade, candidatura.salario, candidatura.anotacoes, candidatura.etapa, candidatura.atualizada_em,
       coalesce(ultima.em, candidatura.criada_em)::timestamptz as etapa_desde
from candidatura
cross join lateral (
    select max(h.em) as em from etapa_historico h where h.candidatura_id = candidatura.id
) ultima
where ($1::text is null or etapa = $1)
  and ($2::text is null
       or empresa ilike '%' || $2 || '%'
       or vaga ilike '%' || $2 || '%')
order by candidatura.atualizada_em desc, candidatura.id desc
`

type ListarCandidaturasParams struct {
	Etapa *string
	Busca *string
}

type ListarCandidaturasRow struct {
	Candidatura Candidatura
	EtapaDesde  time.Time
}

// Filtros opcionais: etapa exata e busca por pedaço do nome da empresa ou da vaga
// (a busca chega com % e _ já escapados, para valerem como texto).
// etapa_desde: quando ela entrou na etapa atual (a última linha do histórico); a tela mostra
// "há N dias nesta etapa". Sem histórico (linha inserida à mão), vale a data do cadastro.
func (q *Queries) ListarCandidaturas(ctx context.Context, arg ListarCandidaturasParams) ([]ListarCandidaturasRow, error) {
	rows, err := q.db.Query(ctx, listarCandidaturas, arg.Etapa, arg.Busca)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarCandidaturasRow
	for rows.Next() {
		var i ListarCandidaturasRow
		if err := rows.Scan(
			&i.Candidatura.ID,
			&i.Candidatura.Empresa,
			&i.Candidatura.Vaga,
			&i.Candidatura.Link,
			&i.Candidatura.CriadaEm,
			&i.Candidatura.Fonte,
			&i.Candidatura.Modalidade,
			&i.Candidatura.Salario,
			&i.Candidatura.Anotacoes,
			&i.Candidatura.Etapa,
			&i.Candidatura.AtualizadaEm,
			&i.EtapaDesde,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mudarEtapa = `-- name: MudarEtapa :one
update candidatura set etapa = $1, atualizada_em = now()
where id = $2
returning id, empresa, vaga, link, criada_em, fonte, modalidade, salario, anotacoes, etapa, atualizada_em
`

type MudarEtapaParams struct {
	Etapa string
	ID    int64
}

func (q *Queries) MudarEtapa(ctx context.Context, arg MudarEtapaParams) (Candidatura, error) {
	row := q.db.QueryRow(ctx, mudarEtapa, arg.Etapa, arg.ID)
	var i Candidatura
	err := row.Scan(
		&i.ID,
		&i.Empresa,
		&i.Vaga,
		&i.Link,
		&i.CriadaEm,
		&i.Fonte,
		&i.Modalidade,
		&i.Salario,
		&i.Anotacoes,
		&i.Etapa,
		&i.AtualizadaEm,
	)
	return i, err
}

const registrarEtapa = `-- name: RegistrarEtapa :one
insert into etapa_historico (candidatura_id, de, para, em, observacao)
values ($1, $2, $3, $4, $5)
returning id, candidatura_id, de, para, em, observacao
`

type RegistrarEtapaParams struct {
	CandidaturaID int64
	De            *string
	Para          string
	Em            time.Time
	Observacao    *string
}

func (q *Queries) RegistrarEtapa(ctx context.Context, arg RegistrarEtapaParams) (EtapaHistorico, error) {
	row := q.db.QueryRow(ctx, registrarEtapa,
		arg.CandidaturaID,
		arg.De,
		arg.Para,
		arg.Em,
		arg.Observacao,
	)
	var i EtapaHistorico
	err := row.Scan(
		&i.ID,
		&i.CandidaturaID,
		&i.De,
		&i.Para,
		&i.Em,
		&i.Observacao,
	)
	return i, err
}

const travarCandidatura = `-- name: TravarCandidatura :one
select id, empresa, vaga, link, criada_em, fonte, modalidade, salario, anotacoes, etapa, atualizada_em from candidatura where id = $1 for update
`

// Para mudar a etapa: trava a linha até o fim da transação, e duas mudanças ao mesmo
// tempo na mesma candidatura acontecem uma depois da outra.
func (q *Queries) TravarCandidatura(ctx context.Context, id int64) (Candidatura, error) {
	row := q.db.QueryRow(ctx, travarCandidatura, id)
	var i Candidatura
	err := row.Scan(
		&i.ID,
		&i.Empresa,
		&i.Vaga,
		&i.Link,
		&i.CriadaEm,
		&i.Fonte,
		&i.Modalidade,
		&i.Salario,
		&i.Anotacoes,
		&i.Etapa,
		&i.AtualizadaEm,
	)
	return i, err
}

const ultimaMudanca = `-- name: UltimaMudanca :one
select coalesce(max(em), '0001-01-01T00:00:00Z'::timestamptz)::timestamptz as em
from etapa_historico where candidatura_id = $1
`

// Sem histórico (linha inserida à mão), o ano 1: o time.Time do Go não representa '-infinity'.
func (q *Queries) UltimaMudanca(ctx context.Context, candidaturaID int64) (time.Time, error) {
	row := q.db.QueryRow(ctx, ultimaMudanca, candidaturaID)
	var em time.Time
	err := row.Scan(&em)
	return em, err
}
