// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contas.sql

package bd

import (
	"context"
	"time"
)

const apagarSessao = `-- name: ApagarSessao :exec
delete from sessao where token_hash = $1
`

func (q *Queries) ApagarSessao(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, apagarSessao, tokenHash)
	return err
}

const apagarSessoesDoUsuario = `-- name: ApagarSessoesDoUsuario :exec
delete from sessao where usuario_id = $1
`

func (q *Queries) ApagarSessoesDoUsuario(ctx context.Context, usuarioID int64) error {
	_, err := q.db.Exec(ctx, apagarSessoesDoUsuario, usuarioID)
	return err
}

const apagarSessoesVencidas = `-- name: ApagarSessoesVencidas :execrows
delete from sessao where expira_em <= $1
`

func (q *Queries) ApagarSessoesVencidas(ctx context.Context, agora time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, apagarSessoesVencidas, agora)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarSessao = `-- name: BuscarSessao :one
select s.usuario_id, u.nome, s.expira_em
from sessao s join usuario u on u.id = s.usuario_id
where s.token_hash = $1 and s.expira_em > $2
`

type BuscarSessaoParams struct {
	TokenHash []byte
	Agora     time.Time
}

type BuscarSessaoRow struct {
	UsuarioID int64
	Nome      string
	ExpiraEm  time.Time
}

func (q *Queries) BuscarSessao(ctx context.Context, arg BuscarSessaoParams) (BuscarSessaoRow, error) {
	row := q.db.QueryRow(ctx, buscarSessao, arg.TokenHash, arg.Agora)
	var i BuscarSessaoRow
	err := row.Scan(&i.UsuarioID, &i.Nome, &i.ExpiraEm)
	return i, err
}

const buscarUsuarioPorNome = `-- name: BuscarUsuarioPorNome :one
select id, nome, senha_hash, criado_em from usuario where nome = $1
`

func (q *Queries) BuscarUsuarioPorNome(ctx context.Context, nome string) (Usuario, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorNome, nome)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.SenhaHash,
		&i.CriadoEm,
	)
	return i, err
}

const contarOutrasContas = `-- name: ContarOutrasContas :one
select count(*) from usuario where nome <> $1
`

func (q *Queries) ContarOutrasContas(ctx context.Context, nome string) (int64, error) {
	row := q.db.QueryRow(ctx, contarOutrasContas, nome)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarSessao = `-- name: CriarSessao :exec
insert into sessao (token_hash, usuario_id, expira_em) values ($1, $2, $3)
`

type CriarSessaoParams struct {
	TokenHash []byte
	UsuarioID int64
	ExpiraEm  time.Time
}

func (q *Queries) CriarSessao(ctx context.Context, arg CriarSessaoParams) error {
	_, err := q.db.Exec(ctx, criarSessao, arg.TokenHash, arg.UsuarioID, arg.ExpiraEm)
	return err
}

const definirSenha = `-- name: DefinirSenha :one
insert into usuario (nome, senha_hash) values ($1, $2)
on conflict (nome) do update set senha_hash = excluded.senha_hash
returning id, nome, senha_hash, criado_em
`

type DefinirSenhaParams struct {
	Nome      string
	SenhaHash string
}

// Cria a conta ou troca a senha de uma que já existe.
func (q *Queries) DefinirSenha(ctx context.Context, arg DefinirSenhaParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, definirSenha, arg.Nome, arg.SenhaHash)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.SenhaHash,
		&i.CriadoEm,
	)
	return i, err
}

const renovarSessao = `-- name: RenovarSessao :exec
update sessao set expira_em = $1 where token_hash = $2
`

type RenovarSessaoParams struct {
	ExpiraEm  time.Time
	TokenHash []byte
}

func (q *Queries) RenovarSessao(ctx context.Context, arg RenovarSessaoParams) error {
	_, err := q.db.Exec(ctx, renovarSessao, arg.ExpiraEm, arg.TokenHash)
	return err
}
