// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lembretes.sql

package bd

import (
	"context"
	"time"
)

const desfazerLembretes = `-- name: DesfazerLembretes :exec
delete from lembrete where id = any($1::bigint[])
`

func (q *Queries) DesfazerLembretes(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, desfazerLembretes, ids)
	return err
}

const lembreteEnviadoDesde = `-- name: LembreteEnviadoDesde :one
select exists (select 1 from lembrete where enviado_em >= $1) as enviado
`

func (q *Queries) LembreteEnviadoDesde(ctx context.Context, desde time.Time) (bool, error) {
	row := q.db.QueryRow(ctx, lembreteEnviadoDesde, desde)
	var enviado bool
	err := row.Scan(&enviado)
	return enviado, err
}

const registrarLembrete = `-- name: RegistrarLembrete :one
insert into lembrete (candidatura_id, historico_id, enviado_em)
values ($1, $2, $3)
returning id
`

type RegistrarLembreteParams struct {
	CandidaturaID int64
	HistoricoID   int64
	EnviadoEm     time.Time
}

func (q *Queries) RegistrarLembrete(ctx context.Context, arg RegistrarLembreteParams) (int64, error) {
	row := q.db.QueryRow(ctx, registrarLembrete, arg.CandidaturaID, arg.HistoricoID, arg.EnviadoEm)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const travarLembretes = `-- name: TravarLembretes :exec
select pg_advisory_xact_lock(7271001)
`

// Trava até o fim da transação: duas instâncias da API não montam o mesmo lembrete ao mesmo tempo.
func (q *Queries) TravarLembretes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, travarLembretes)
	return err
}

const ultimaMudancaDeCada = `-- name: UltimaMudancaDeCada :many
with ultima as (
    select distinct on (candidatura_id) candidatura_id, id as historico_id, para, em
    from etapa_historico
    order by candidatura_id, em desc, id desc
)
select c.id, c.empresa, c.vaga, u.historico_id, u.para as etapa, u.em,
    coalesce((select max(l.enviado_em) from lembrete l where l.historico_id = u.historico_id),
        '0001-01-01T00:00:00Z'::timestamptz)::timestamptz as ultimo_lembrete
from ultima u
join candidatura c on c.id = u.candidatura_id
order by u.em, c.id
`

type UltimaMudancaDeCadaRow struct {
	ID             int64
	Empresa        string
	Vaga           string
	HistoricoID    int64
	Etapa          string
	Em             time.Time
	UltimoLembrete time.Time
}

// A última mudança de etapa de cada candidatura e quando ela foi lembrada pela última vez
// (ano 1 = nunca). As regras de "parada há quantos dias" ficam no Go (pacote lembretes).
func (q *Queries) UltimaMudancaDeCada(ctx context.Context) ([]UltimaMudancaDeCadaRow, error) {
	rows, err := q.db.Query(ctx, ultimaMudancaDeCada)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UltimaMudancaDeCadaRow
	for rows.Next() {
		var i UltimaMudancaDeCadaRow
		if err := rows.Scan(
			&i.ID,
			&i.Empresa,
			&i.Vaga,
			&i.HistoricoID,
			&i.Etapa,
			&i.Em,
			&i.UltimoLembrete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
