// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package bd

import (
	"time"
)

type Candidatura struct {
	ID           int64
	Empresa      string
	Vaga         string
	Link         *string
	CriadaEm     time.Time
	Fonte        *string
	Modalidade   *string
	Salario      *string
	Anotacoes    *string
	Etapa        string
	AtualizadaEm time.Time
}

type EtapaHistorico struct {
	ID            int64
	CandidaturaID int64
	De            *string
	Para          string
	Em            time.Time
	Observacao    *string
}

type Lembrete struct {
	ID            int64
	CandidaturaID int64
	HistoricoID   int64
	EnviadoEm     time.Time
}

type Sessao struct {
	TokenHash []byte
	UsuarioID int64
	CriadaEm  time.Time
	ExpiraEm  time.Time
}

type Usuario struct {
	ID        int64
	Nome      string
	SenhaHash string
	CriadoEm  time.Time
}
