// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: numeros.sql

package bd

import (
	"context"
	"time"
)

const enviadasPorSemana = `-- name: EnviadasPorSemana :many
select p.semana::date as semana, count(*) as total
from (
    select date_trunc('week', min(em) at time zone 'America/Sao_Paulo') as semana
    from etapa_historico
    where para = 'enviada'
    group by candidatura_id
    having min(em) >= $1
) p
group by p.semana
order by p.semana
`

type EnviadasPorSemanaRow struct {
	Semana time.Time
	Total  int64
}

// O primeiro envio de cada candidatura (voltar para "enviada" não conta de novo), em semanas
// de segunda a domingo no horário de Brasília.
func (q *Queries) EnviadasPorSemana(ctx context.Context, desde time.Time) ([]EnviadasPorSemanaRow, error) {
	rows, err := q.db.Query(ctx, enviadasPorSemana, desde)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnviadasPorSemanaRow
	for rows.Next() {
		var i EnviadasPorSemanaRow
		if err := rows.Scan(&i.Semana, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const funil = `-- name: Funil :many

with alcance as (
    select h.candidatura_id,
        max(($1::int[])[array_position($2::text[], h.para)]) as maximo
    from etapa_historico h
    group by h.candidatura_id
)
select p.nivel::int as nivel, count(*) filter (where a.maximo >= p.nivel) as total
from (select distinct n as nivel from unnest($1::int[]) as n) p
cross join alcance a
group by p.nivel
order by p.nivel
`

type FunilParams struct {
	Niveis []int32
	Etapas []string
}

type FunilRow struct {
	Nivel int32
	Total int64
}

// O "alcance" de cada candidatura é o nível mais adiantado que ela já atingiu no histórico. Os
// níveis vêm do Go (numeros.niveis, montado a partir de candidaturas.Etapas) em duas listas do
// mesmo tamanho, @etapas e @niveis: o nível de uma etapa é (@niveis)[posição dela em @etapas].
// A ordem fica num lugar só. Etapa sem nível (desisti) dá null, que o max ignora.
// Quantas candidaturas chegaram a cada nível (pular uma etapa conta como ter passado por ela).
// distinct: recusada tem o mesmo nível de enviada, e sem ele o nível repetido contaria em dobro
func (q *Queries) Funil(ctx context.Context, arg FunilParams) ([]FunilRow, error) {
	rows, err := q.db.Query(ctx, funil, arg.Niveis, arg.Etapas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FunilRow
	for rows.Next() {
		var i FunilRow
		if err := rows.Scan(&i.Nivel, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const porEtapaAtual = `-- name: PorEtapaAtual :many
select etapa, count(*) as total from candidatura group by etapa
`

type PorEtapaAtualRow struct {
	Etapa string
	Total int64
}

func (q *Queries) PorEtapaAtual(ctx context.Context) ([]PorEtapaAtualRow, error) {
	rows, err := q.db.Query(ctx, porEtapaAtual)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PorEtapaAtualRow
	for rows.Next() {
		var i PorEtapaAtualRow
		if err := rows.Scan(&i.Etapa, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const porFonte = `-- name: PorFonte :many
with alcance as (
    select c.id, nullif(lower(btrim(c.fonte)), '') as chave, btrim(c.fonte) as fonte,
        max(($5::int[])[array_position($6::text[], h.para)]) as maximo
    from candidatura c
    join etapa_historico h on h.candidatura_id = c.id
    group by c.id
)
select coalesce(mode() within group (order by fonte), '')::text as fonte,
    count(*) filter (where maximo >= $1::int) as enviadas,
    count(*) filter (where maximo >= $2::int) as entrevistas,
    count(*) filter (where maximo >= $3::int) as propostas,
    count(*) filter (where maximo >= $4::int) as contratados
from alcance
group by chave
having count(*) filter (where maximo >= $1::int) > 0
order by enviadas desc, chave nulls last
`

type PorFonteParams struct {
	NivelEnviada    int32
	NivelEntrevista int32
	NivelProposta   int32
	NivelContratado int32
	Niveis          []int32
	Etapas          []string
}

type PorFonteRow struct {
	Fonte       string
	Enviadas    int64
	Entrevistas int64
	Propostas   int64
	Contratados int64
}

// Fontes iguais sem diferenciar maiúsculas nem espaços nas pontas ("LinkedIn" e " linkedin ");
// o nome mostrado é a grafia mais usada. Sem fonte = ”.
func (q *Queries) PorFonte(ctx context.Context, arg PorFonteParams) ([]PorFonteRow, error) {
	rows, err := q.db.Query(ctx, porFonte,
		arg.NivelEnviada,
		arg.NivelEntrevista,
		arg.NivelProposta,
		arg.NivelContratado,
		arg.Niveis,
		arg.Etapas,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PorFonteRow
	for rows.Next() {
		var i PorFonteRow
		if err := rows.Scan(
			&i.Fonte,
			&i.Enviadas,
			&i.Entrevistas,
			&i.Propostas,
			&i.Contratados,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tempoDeResposta = `-- name: TempoDeResposta :one
with envio as (
    select distinct on (candidatura_id) candidatura_id, em as enviada_em, id as enviada_id
    from etapa_historico where para = 'enviada'
    order by candidatura_id, em, id
),
resposta as (
    select e.candidatura_id, e.enviada_em, c.etapa,
        (select min(h.em) from etapa_historico h
         where h.candidatura_id = e.candidatura_id and (h.em, h.id) > (e.enviada_em, e.enviada_id)
           and h.para not in ('interesse', 'enviada', 'desisti')) as respondida_em
    from envio e join candidatura c on c.id = e.candidatura_id
)
select count(respondida_em) as respondidas,
    count(*) filter (where respondida_em is null and etapa = 'enviada') as aguardando,
    -- 0 quando nenhuma foi respondida (aí o Go devolve null)
    coalesce(avg(extract(epoch from respondida_em - enviada_em)) / 86400, 0)::float8 as media_dias,
    coalesce(percentile_cont(0.5) within group (order by extract(epoch from respondida_em - enviada_em)) / 86400, 0)::float8 as mediana_dias
from resposta
`

type TempoDeRespostaRow struct {
	Respondidas int64
	Aguardando  int64
	MediaDias   float64
	MedianaDias float64
}

// Do primeiro "enviada" até a primeira mudança depois dele que veio da empresa (qualquer etapa,
// menos voltar para interesse/enviada ou "desisti", que é decisão minha). Em dias. "Depois" é
// por (em, id): duas mudanças no mesmo instante ficam na ordem em que foram registradas.
func (q *Queries) TempoDeResposta(ctx context.Context) (TempoDeRespostaRow, error) {
	row := q.db.QueryRow(ctx, tempoDeResposta)
	var i TempoDeRespostaRow
	err := row.Scan(
		&i.Respondidas,
		&i.Aguardando,
		&i.MediaDias,
		&i.MedianaDias,
	)
	return i, err
}
